import type { EMapAvatarDefinition } from "../types";

export const EMAP_AVATAR_DEFINITIONS: EMapAvatarDefinition[] = [
  {
    id: "avatar-main-brain",
    name: "LLBoss Command Tower",
    entityType: "main_brain",
    animationStates: ["idle", "thinking", "error"],
    defaultTrainType: "shinkansen",
    colorToken: "mainBrain",
    emojiFallback: "B",
  },
  {
    id: "avatar-agent",
    name: "PocketFlow Agent",
    entityType: "agent",
    animationStates: ["idle", "moving", "thinking", "error", "offline"],
    defaultTrainType: "steam",
    colorToken: "builder",
    emojiFallback: "A",
  },
  {
    id: "avatar-builder",
    name: "Pixel Builder",
    entityType: "agent",
    animationStates: ["idle", "moving", "thinking", "repairing", "error"],
    defaultTrainType: "shinkansen",
    colorToken: "builder",
    emojiFallback: "B",
  },
  {
    id: "avatar-fixer",
    name: "Pixel Fixer",
    entityType: "agent",
    animationStates: ["idle", "moving", "repairing", "error"],
    defaultTrainType: "steam",
    colorToken: "fixer",
    emojiFallback: "F",
  },
  {
    id: "avatar-monitor",
    name: "Monitor Drone",
    entityType: "monitor_agent",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "shinkansen",
    colorToken: "monitor",
    emojiFallback: "M",
  },
  {
    id: "avatar-transport",
    name: "Transport Collector",
    entityType: "monitor_agent",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "automation",
    emojiFallback: "TR",
  },
  {
    id: "avatar-learning",
    name: "Learning Supervisor",
    entityType: "monitor_agent",
    animationStates: ["idle", "moving", "thinking", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "memory",
    emojiFallback: "LR",
  },
  {
    id: "avatar-style-teacher",
    name: "Owner Style Teacher",
    entityType: "monitor_agent",
    animationStates: ["idle", "moving", "thinking", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "memory",
    emojiFallback: "ST",
  },
  {
    id: "avatar-preference-teacher",
    name: "Preference Pattern Teacher",
    entityType: "monitor_agent",
    animationStates: ["idle", "moving", "thinking", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "memory",
    emojiFallback: "PF",
  },
  {
    id: "avatar-yard",
    name: "Parking Yard Marker",
    entityType: "queue",
    animationStates: ["idle", "offline"],
    defaultTrainType: "cargo",
    colorToken: "unknown",
    emojiFallback: "PK",
  },
  {
    id: "avatar-news",
    name: "News Flow Agent",
    entityType: "agent",
    animationStates: ["idle", "moving", "thinking", "error", "offline"],
    defaultTrainType: "steam",
    colorToken: "automation",
    emojiFallback: "N",
  },
  {
    id: "avatar-newsletter",
    name: "Newsletter Agent",
    entityType: "automation",
    animationStates: ["idle", "moving", "thinking", "error", "offline"],
    defaultTrainType: "steam",
    colorToken: "automation",
    emojiFallback: "NL",
  },
  {
    id: "avatar-moltbook",
    name: "Moltbook Posting Agent",
    entityType: "automation",
    animationStates: ["idle", "moving", "thinking", "error", "offline"],
    defaultTrainType: "steam",
    colorToken: "automation",
    emojiFallback: "MB",
  },
  {
    id: "avatar-crm",
    name: "CRM Agent",
    entityType: "agent",
    animationStates: ["idle", "moving", "thinking", "error", "offline"],
    defaultTrainType: "steam",
    colorToken: "automation",
    emojiFallback: "C",
  },
  {
    id: "avatar-relay",
    name: "Relay Agent",
    entityType: "server",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "shinkansen",
    colorToken: "server",
    emojiFallback: "R",
  },
  {
    id: "avatar-radar",
    name: "Radar Agent",
    entityType: "agent",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "shinkansen",
    colorToken: "monitor",
    emojiFallback: "FL",
  },
  {
    id: "avatar-payments",
    name: "Payments Agent",
    entityType: "security",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "security",
    emojiFallback: "$",
  },
  {
    id: "avatar-memory",
    name: "Archive Keeper",
    entityType: "memory",
    animationStates: ["idle", "moving", "thinking", "error"],
    defaultTrainType: "cargo",
    colorToken: "memory",
    emojiFallback: "L",
  },
  {
    id: "avatar-tool",
    name: "Tool Operator",
    entityType: "tool",
    animationStates: ["idle", "moving", "thinking", "error"],
    defaultTrainType: "steam",
    colorToken: "mainBrain",
    emojiFallback: "T",
  },
  {
    id: "avatar-model-runner",
    name: "Model Power Core",
    entityType: "model",
    animationStates: ["idle", "moving", "thinking", "error", "offline"],
    defaultTrainType: "shinkansen",
    colorToken: "model",
    emojiFallback: "Q",
  },
  {
    id: "avatar-server",
    name: "Server Antenna",
    entityType: "server",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "shinkansen",
    colorToken: "server",
    emojiFallback: "S",
  },
  {
    id: "avatar-security",
    name: "Policy Guard",
    entityType: "security",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "security",
    emojiFallback: "P",
  },
  {
    id: "avatar-malware",
    name: "Malware Sentinel",
    entityType: "monitor_agent",
    animationStates: ["idle", "moving", "scanning", "error", "offline"],
    defaultTrainType: "cargo",
    colorToken: "security",
    emojiFallback: "MW",
  },
  {
    id: "avatar-unknown",
    name: "Unknown Station Worker",
    entityType: "unknown",
    animationStates: ["idle", "offline", "error"],
    defaultTrainType: "steam",
    colorToken: "unknown",
    emojiFallback: "?",
  },
];

export const getEMapAvatarDefinition = (id?: string) =>
  EMAP_AVATAR_DEFINITIONS.find((avatar) => avatar.id === id) || EMAP_AVATAR_DEFINITIONS.at(-1)!;
